In [9]:
# 넘파이 패키지 임포트
import numpy as np

# 1차원 배열 만들기 1X3
d1_ar = np.array([0,1,2,3])

# 2차원 배열 만들기 2X3 = 행 X 열
d2_ar = np.array([[0, 1, 2],[3, 4, 5]])

# 3차원 배열 만들기 2X3X4 = 김이 X 행 X 열
d3_ar = np.array([[[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]],[[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])

# 배열의 차원 반환 .ndim
print(d2_ar.ndim)

# 배열의 크기 반환 .shape
print(d3_ar.shape)  

2
(2, 3, 4)


In [21]:
# 넘파이 패키지 임포트
import numpy as np

# 1차원 배열 만들기 1X3
d1_ar = np.array([0,1,2,3])

# 2차원 배열 만들기 2X3 = 행 X 열
d2_ar = np.array([[0, 1, 2],[3, 4, 5]])

# 3차원 배열 만들기 2X3X4 = 김이 X 행 X 열
d3_ar = np.array([[[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]],[[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])

# 배열 인덱싱
print(d1_ar[2])
print(d2_ar[1, 2])
print(d3_ar[1, 2, 3])

# 배열 슬라이싱
print(d2_ar[1, :]) # 두번째 행 모든 열 출력
print(d3_ar[1, 1, 1:]) #두번째 깊이, 두번째 행, 두번째 열부터 끝 열까지 출력

2
5
23
[3 4 5]
[17 18 19]


In [23]:
# 넘파이 패키지 임포트
import numpy as np

# 1차원 배열 만들기 1X3
d1_ar = np.array([0,1,2,3])

# 팬시 인덱싱
print(d1_ar % 2 == 0) # 짝수면 원소가 True, 홀수면 원소가 False로 배열이 생성
print(d1_ar[d1_ar % 2 == 0]) # 팬시 인덱싱으로 원소가 True인 것만 배열을 생성하여 출력

[ True False  True False]
[0 2]


In [34]:
# 넘파이 패키지 임포트
import numpy as np

# boolean형 1차원 배열 생성
d1_bool_ar = np.array([True, 1, 0, 1], dtype = 'b')
print(d1_bool_ar) # [1 1 0 1] 출력

# int형 1차원 배열 생성
d1_int_ar = np.array([1.0, 2.3, 3.4], dtype = 'i')
print(d1_int_ar) # [1 2 3] 출력

# float형 1차원 배열 생성
d1_float_ar = np.array([1, 2, 3], dtype = 'f')
print(d1_float_ar) # [1. 2. 3. ] 출력

# 복소 부동소수점(128비트) 1차원 배열 생성
d1_cfloat_ar = np.array([1, 2, 3], dtype = 'c')
print(d1_cfloat_ar) # [b'1' b'2' b'3']

[1 1 0 1]
[1 2 3]
[1. 2. 3.]
[b'1' b'2' b'3']


In [49]:
# 넘파이 패키지 임포트
import numpy as np

# 크기가 정해져 있고 모든 값이 0인 1차원 배열 생성, 기본값으로 원소는 float 형이다.
d1_zeros_ar = np.zeros(3) 
print(d1_zeros_ar) # [0. 0. 0. ] 출력
print(d1_zeros_ar.dtype) # float64 출력

# 크기가 정해져 있고 모든 값이 1인 2X3 2차원 배열 생성, 원소를 int32 형으로 설정
d2_ones_ar = np.ones((2, 3), dtype = 'i')
print(d1_ones_ar) # [[1 1 1], [1 1 1]] 출력
print(d1_ones_ar.dtype) # int32 출력

# 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 원소 0인 배열을 생성
d2_zeros2_ar = np.zeros_like(d2_ones_ar, dtype = 'f')
print(d2_zeros2_ar) # [[0. 0. 0. ], [0. 0. 0. ]] 출력
print(d2_zeros2_ar.dtype) # float64 출력

[0. 0. 0.]
float64
[[1 1 1]
 [1 1 1]]
int32
[[0. 0. 0.]
 [0. 0. 0.]]
float32


In [52]:
# 넘파이 패키지 임포트
import numpy as np

# arrange 명령
# 0부터 시작 10미만
ex1 = np.arange(10)
print(ex1)

# 2부터 시작, 20미만, 등차 3 
ex2 = np.arange(2, 20, 3)
print(ex2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  5  8 11 14 17]


In [57]:
# 넘파이 패키지 임포트
import numpy as np

# 전치 연산
# 2행 3열 2차원 배열 생성
ex3 = np.array([[1, 2, 3], [4, 5, 6]])

# 3행 2열 2차원 전치 행렬 생성
ex4 = ex3.T
print(ex4)

[[1 4]
 [2 5]
 [3 6]]


In [68]:
# 넘파이 패키지 임포트
import numpy as np

# 배열의 크기 변형

# 10개 원소 1차원 배열 생성
d1_ar = np.arange(10)

# reshape 메서드로 2행 5열 2차원 배열로 변환
d2_ar = d1_ar.reshape(2,5)

# reshape 메서드 -1 인수는 나머지 원소를 알아서 계산하여 변환
d2_ar_2 = d1_ar.reshape(5, -1) # 5행 2열로 배열로 변환

# flatten, ravel 메서드로 다차원 배열을 1차원 배열로 만들기
d1_flatten = d2_ar.flatten()
d1_ravel = d2_ar.ravel()

# newaxis 명령으로 1차원 증가시키기
d1_ar = d1_ar[:, np.newaxis]

In [73]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 2X3 원소 0 배열 생성
a1 = np.zeros((2, 3), dtype = 'i')
# 2X4 원소 1 배열 생성
a2 = np.ones((2, 4), dtype = 'i')

# hstack 명령 : 행의 수가 같아야 함 : 열 원소 연결
print(np.hstack([a1, a2]))

[[0 0 0 1 1 1 1]
 [0 0 0 1 1 1 1]]


In [77]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 3X2 원소 0 배열 생성
a1 = np.zeros((3, 2), dtype = 'i')
a2 = np.ones((4, 2), dtype = 'i')

# vstack 명령 : 열의 수가 같아야 함 : 행 원소 연결
print(np.vstack([a1, a2]))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [79]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 2X3 원소 0 배열 생성
a1 = np.zeros((2, 3), dtype = 'i')
# 2X3 원소 1 배열 생성
a2 = np.ones((2, 3), dtype = 'i')

# dstack 명령 : 행과 열 다 같아야함 : 마지막 차원 증가 : 2X3X2
print(np.dstack([a1, a2]))

[[[0 1]
  [0 1]
  [0 1]]

 [[0 1]
  [0 1]
  [0 1]]]


In [83]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 2X3 원소 0 배열 생성
a1 = np.zeros((2, 3), dtype = 'i')
# 2X3 원소 1 배열 생성
a2 = np.ones((2, 3), dtype = 'i')

# stack 명령 : 행과 열 다 같아야함 : axis 인수로 원하는 차원 증가
print(np.stack([a1, a2], axis = 1)) # axis = 1로 두번째 차원 증가 2X2X3

[[[0 0 0]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]]]


In [85]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 1차원 배열 생성
a1 = np.ones(3)
a2 = np.zeros(3)

# r_ 메서드, [ ] 중괄호 사용, hstack 명령과 비슷하게 배열 좌우 연결
print(np.r_[a1, a2])

[1. 1. 1. 0. 0. 0.]


In [87]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 1차원 배열 생성
a1 = np.ones(3)
a2 = np.zeros(3)

# c_ 메서드, [ ] 중괄호 사용, 차원을 증가시킨 후 좌우 연결
print(np.c_[a1, a2])

[[1. 0.]
 [1. 0.]
 [1. 0.]]


In [90]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 연결

# 1차원 배열 생성
a1 = np.ones(3)

# tile 명령, 동일한 배열을 반복하여 연결
print(np.tile(a1, 2))

[1. 1. 1. 1. 1. 1.]


In [1]:
# 넘파이 패키지 임포트
import numpy as np

# 2차원 그리드 포인트 생성
x = np.arange(1, 4)
y = np.arange(4, 10)

# X좌표, Y좌표 그리드 포인트 배열 각각 생성
X, Y = np.meshgrid(x, y)

# X, Y 배열을 합쳐서 포인트 배열 생성
# 2차원 그리드 포인트 배열 생성, 그래프에서 X 값, Y값이라고 생각하면 된다.
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(1, 4), (2, 4), (3, 4)],
 [(1, 5), (2, 5), (3, 5)],
 [(1, 6), (2, 6), (3, 6)],
 [(1, 7), (2, 7), (3, 7)],
 [(1, 8), (2, 8), (3, 8)],
 [(1, 9), (2, 9), (3, 9)]]

In [3]:
# 넘파이 패키지 임포트
import numpy as np

x = np.arange(1, 101)
y = np.arange(201, 301)

print(x)
print(y)
print(x+y) # 벡터 연산이 수행된다.
# 사칙연산이 모두 가능하다.

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 291 292 293 294 295 296 297 298 299 300]
[202 204 206 208 210 212 214 216 218 220 222 224 226 228 230 232 234 236
 238 240 242 244 246 248 250 252 254 256 258 260 262 264 266 268 270 272
 274 276 278 280 282 284 286 288 290 292

In [5]:
# 넘파이 패키지 임포트
import numpy as np

# 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령 이용
x = np.arange(1, 101)
y = np.arange(1, 101)

print(np.all(x == y)) # True 출력

True


In [7]:
# 넘파이 패키지 임포트
import numpy as np

# 벡터의 크기가 다를 때 자동으로 브로드캐스팅이 된다.
x = np.arange(1, 101)
y = 1

# 브로드캐스팅
print(x+y)

[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101]


In [21]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 생성
x = np.arange(1, 101)

print(np.sum(x)) #행 합계 출력 5050
print(np.min(x)) #행 최솟값 출력 1
print(np.max(x)) #행 최댓값 출력 100
print(np.argmin(x)) #행 최솟값의 인덱스 0
print(np.argmax(x)) #행 최댓값의 인덱스 99
print(np.mean(x)) # 행 평균 50.5
print(np.median(x)) # 행 중간값 50.5
print(len(x)) # 데이터의 개수 출력 100
print(np.var(x)) # 표본 분산 출력 833.35
print(np.std(x)) #표본 표준편자 출력 28.866

5050
1
100
0
99
50.5
50.5
100
833.25
28.86607004772212
1.0
25.75


In [17]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 생성
x = np.array([[1, 3, 6, 2], [5, 7, 2, 1], [3, 2, 5, 6]])

a = np.sort(x) # 행 기준 정렬
b = np.sort(x, axis = 0) # 열 기준 정렬

# 배열 생성
y = np.array([3, 5, 2, 7])

c = np.argsort(y) # 정렬 순서 인덱스 생성

In [24]:
# 넘파이 패키지 임포트
import numpy as np

# 시드 설정하기
np.random.seed(10)

np.random.rand(5) # 5개의 랜덤 변수 생성

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [30]:
# 넘파이 패키지 임포트
import numpy as np

# 배열 생성
x = np.arange(5)

# 순서 섞기
np.random.shuffle(x)

In [36]:
# 넘파이 패키지 임포트
import numpy as np

# 시드 설정
np.random.seed(0)

# 랜덤 배열 생성
x = np.random.rand(10)

# 데이터 샘플링
y = np.random.choice(x, 5, replace = True, p = [0.5, 0, 0.1, 0.1, 0.2, 0.1, 0, 0, 0, 0])

p

[0.4236548  0.60276338 0.60276338 0.64589411 0.5488135 ]
